### PR TITLE
Bump gcc to 9.2.0

### PR DESCRIPTION
**Pull request by kito-cheng**
Bump GCC to 9.2.0 for next release :)

### CODE REVIEW

**Comment by kito-cheng** [comment]
I thought `RGT_VERSION` should update, but I am not sure what value should be filled, it was `8.3.0-2019.11.0-preview5`, so `9.2.0-2020.02.0-preview1` or any other suggestion?

**Comment by cgsfv** [comment]
I would update RGT_VERSION to 9.2.0-2019.11.0-preview1
Have you checked that it builds on tpp01 and tpp03 before merging into master?

**Comment by kito-cheng** [comment]
tpp01 and tpp03 are pass :)
tpp01: https://jenkins.internal.sifive.com/job/freedom-tools/job/tpp01--toolchain-only-package--kito/2/
tpp03: https://jenkins.internal.sifive.com/job/freedom-tools/job/tpp03--toolchain-only-package--kito/2/

**Comment by cgsfv** [comment]
LGTM - I have merged the changes into master.

**Pull request merged**
