### PR TITLE
Enable python support in gdb and gdb only builds

### PR DESCRIPTION
**Pull request by cgsfv**

### CODE REVIEW

**Comment by ilg-ul** [comment]
Did you check if the gdb-py binary built on CentOS runs on a Debian? Since I encountered problems with my CentOS binaries, they run on Arch but fail on Ubuntu and Debian.

https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/issues/5

**Comment by cgsfv** [comment]
I only checked that it actually runs on CentOS - haven't checked on Debian. But is is meant to be used together with the new python package that is also built from freedom-tools. I will check that it works on Debian before the next official release.

**Comment by ilg-ul** [comment]
> is meant to be used together with the new python package that is also built from freedom-tools

Ah, I missed this. 

This trick might help, but I don't think it is a very nice one. Normally gdb-py should run with the system installed Python.

**Comment by cgsfv** [comment]
I chose this way, because we wanted Python 2.7 support, and CentOS 6 only has Python 2.6. And on Windows we also need to provide a Python package anyways.
So to keep things simpler, the solution is a provide all components that are not naturally part of a platform.
I agree, the Ubuntu packages was a wrong thing to distribute, but it was something I chose to do before I had the complete overview of dependencies and packages built...
And they were built as part of the Windows cross-compilation build step on Ubuntu.

**Comment by ilg-ul** [comment]
> we wanted Python 2.7 support, and CentOS 6 only has Python 2.6

Yes, for CentOS/RHEL 6 that makes sense, but if you already have a Python 2.7 available (and most modern distributions do), there should be no need for a custom Python.

**Pull request merged**
