### PR TITLE
Bump GCC for fixing mac build issue

### PR DESCRIPTION
**Pull request by kito-cheng**

### CODE REVIEW

**Comment by kito-cheng** [comment]
CI job for this PR: https://jenkins.internal.sifive.com/job/tpp-freedom-tools/job/tpp00--all-build-and-upload--parameterized/140/

**Comment by kito-cheng** [comment]
Note: mac build was failed after 10 sec, but it cause by unknown Permission issue:
https://jenkins.internal.sifive.com/job/tpp-freedom-tools/job/tpp01--build-binary-packages--parameterized/139/console
I've restart it again and seems so far so good:
https://jenkins.internal.sifive.com/job/tpp-freedom-tools/job/tpp01--build-binary-packages--parameterized/140/console

**Comment by cgsfv** [comment]
Yes, the new Mac build worked, along with the ones on CentOS and Ubuntu (+Windows).
I have copied the Mac tarballs to /work/dev-tools/preview/freedom-tools-packages/parameterized-140-toolchain
So they are all available for all platforms in that directory.
Will you inform all the ones that need this toolchain build, where they can get it?

**Comment by issuehsu** [comment]
I've copied them to /work/experiment_tools/ASAP, and I will inform all the ones that need it.
Thanks Kito and Carsten.

**Pull request merged**
