### PR TITLE
Koala tdc

### PR DESCRIPTION
**Pull request by sifivekevin**
Use master branch of trace-decoder repo and bumped version to 0.9.0-2020-04.0

### CODE REVIEW

**Comment by cgsfv** [comment]
I think you need to do a rebase first, as there are merge conflicts.

**Comment by sifivekevin** [comment]
I do not understand the merge conflicts (they are in src folders unrelated to the trace-decoder.  And attempts to rebase have failed so far.  I'll keep trying.

**Comment by sifivekevin** [comment]
I think I've got a successful rebase done now.  I'm waiting for an existing binutils build to finish before my trace-decoer build kicks off.

**Comment by cgsfv** [comment]
Binutils, gdb, newlib and openocd submodules are not pointing to the same commit id's as they do in the master branch.

**Comment by cgsfv** [comment]
Sorry, gdb is still not pointing to the same

**Pull request merged**
