### PR TITLE
Trace decoder libs

### PR DESCRIPTION
**Pull request by bradseevers**
Makefile mods to create position independant code libs on ubuntu for trace decoder.

### CODE REVIEW

**Comment by cgsfv** [comment]
The src/trace-decoder submodule is still pointing to a very old version.
Please update it to point to the correct commit of the trace-decoder.

**Comment by bradseevers** [comment]
Okay - no problem! But I have just passed my knowledge of git! Do I make
this change in the trace-decoder, or in freedom-tools? Can you give me a
hint on how to do this?

Thanks!

-brad

**Comment by cgsfv** [comment]
I have found this webpage, which I found very useful with a very good explanation on how to do this:
[https://chrisjean.com/git-submodules-adding-using-removing-and-updating/]

You need to the change in freedom-tools:
- cd src/trace-decoder
- git checkout master
- git pull
- if you want something else than master: git checkout <commit>
- cd ../..
- git add src/trace-decoder     (without a trailing / !!!!)
- git commit -m "your commit message"
- git push

**Comment by bradseevers** [comment]
Carsten,

I followed your instructions. The trace-decoder-libs branch has been
updated to use the latest version of trace-decoder master.

Let me know if I messed anything up!

Thanks,

-brad

**Comment by bradseevers** [comment]
I'm guessing I need to cancel my PR and create a new one?

-brad

**Comment by cgsfv** [comment]
No, the PR is fine - it is updated with the update of the trace-decoder submodule.
I will continue my look at your solution.

**Comment by cgsfv** [comment]
When building on my mac, I got this error: swig not found

**Comment by sifivekevin** [comment]
You might have to install swig on the Mac.  Probably available via Homebrew.

**Comment by cgsfv** [comment]
OK - which version of SWIG are you using?

**Comment by sifivekevin** [comment]
The latest version should be fine.  We can check when we get back to
the offices.

**Comment by cgsfv** [comment]
Install SWIG.
Next error: JNIINCLUDE not defined

**Comment by bradseevers** [comment]
If JNIINCLUDE is not defined, it just skips building the swig shared
library. More informational than an error, unless you are trying to build
the swig shared libary - which you are!

Set JNIINCLUDE to the path to the java include files on your system.  For
example, on my linux system I do a:

export JNIINCLUDE="/usr/lib/jvm/java-11-openjdk-amd64/include

-brad

**Comment by cgsfv** [comment]
I would expect this to be setup/handled in the trace-decoder Makefile.
Can you do that - I guess there must be some way to query java about that?

**Comment by sifivekevin** [comment]
I don't know if you can query Java for that path.  I've always had to rely
on environment variables set on each system to point to the right place.
And using said envar allows every developer to configure their system as
they see fit (putting java where they like it)..

**Comment by bradseevers** [comment]
My thoughts were I didn't want to do it in the makefile. I wanted the user
to be able to control whether or not they wanted to build the java stuff.
If it isn't set, it skips it. If they aren't interested in Java, they don't
need to worry about swig or java.

-brad

**Comment by bradseevers** [comment]
I think I could do it in the makefile if that is what we want to do.

-brad

**Comment by cgsfv** [comment]
I also like to be able to configure stuff myself.
But the purpose of freedom-tools is that it should be easy to build the tools.
Meaning that there should be a default configuration that builds everything as it should be - meaning what we release and use in Freedom Studio - without any additional configuration needed.

I have it on my list to also add checking of all the dependencies listed in the README.md file.

**Comment by bradseevers** [comment]
I will see if I can add the JNIINCLUDE computation to the makefile.

-brad

**Comment by bradseevers** [comment]
Well, I have a really nice solution, except it doesn't work! It works fine
if there are no spaces in the path to the java include directory. Make's
$(abspath X) treats X as multiple arguments if it contains spaces, and give
a completely different answer than desired. There doesn't seem to be any
way to quote spaces in make. (You can quote like crazy, but it doesn't seem
to make a difference)

Since on windows java installs in  \program files\, which contains a space,
this is a problem. Is working great on linux.

I haven't given up yet.

-brad

**Comment by sifivekevin** [comment]
I think it is OK to mandate (for people wanting to build freedom-tools, or
the trace-decode standalone) that dependencies be installed in paths that
contain no spaces.  That "requirement" is almost ubiquitous in the GNU
world.  What do you think, Carsten?

**Comment by sifivekevin** [comment]
BTW: On my windows machine I make sure everything needed to build is
installed in space-free locations.

**Comment by bradseevers** [comment]
You don't install in c:\Program Files\?

**Comment by sifivekevin** [comment]
NEVER!  Unless it is a native Windows app unrelated to any development work
I do. I might be a Windows fanboy, but I know when cry "Uncle". :)

**Comment by cgsfv** [comment]
I fully agree!
And btw. freedom-tools is not specified to build on windows.
We only support building on linux and mac.
So it's fine if it only works if there are no spaces in the paths.

**Comment by bradseevers** [comment]
Just updated makefile.init in the tace-encoder to compute JNIINCLUDE based
on where it finds javac. This does not work if there are spaces in the
path. JNIINCLUDE can be overridden by setting it in the environment or
passing it on the make command line (but you shouldn't need to).

Carston, do I need to generate a new PR?

Thanks,

-brad

**Comment by cgsfv** [comment]
No, you just need to update the trace-decoder submodule to point to the new commit of that.

**Comment by bradseevers** [comment]
Will do!

**Comment by bradseevers** [comment]
Carsten,

I think I have updated the freedom-tools trace-decoder submodule to point
to the updated trace-decoder. Let me know if I messed it up!

-brad

**Comment by cgsfv** [comment]
I got further with the build, but it stops with this error in the make-build.log:
Building file dqr_wrap.o
Invoking: GCC C++ Compiler
g++ -D OSX -std=c++11 -O0 -g3 -Wall -Wformat=0 -D OSX -std=c++11 -O0 -g3 -Wall -Wformat=0 -c dqr_wrap.cpp -I"../include" -I"/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac" -I"/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac/darwin"
dqr_wrap.cpp:181:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^~~~~~~
1 error generated.

When I run java --version on my Mac, I get:
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20191016_371 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)

**Comment by bradseevers** [comment]
Could you send me your entire make.log for the trace decoder?

Also, where on your system is java installed?

Thanks,

-brad

**Comment by cgsfv** [comment]
/Library/Developer/CommandLineTools/usr/bin/make -C lib NEWLIBPATH=/scratch/carsteng/git/freedom-tools-tdl/obj/x86_64-apple-darwin/build/riscv-gnu-toolchain/build-binutils-newlib all
cp /scratch/carsteng/git/freedom-tools-tdl/obj/x86_64-apple-darwin/build/riscv-gnu-toolchain/build-binutils-newlib/bfd/libbfd.a macos
cp /scratch/carsteng/git/freedom-tools-tdl/obj/x86_64-apple-darwin/build/riscv-gnu-toolchain/build-binutils-newlib/opcodes/libopcodes.a macos
cp /scratch/carsteng/git/freedom-tools-tdl/obj/x86_64-apple-darwin/build/riscv-gnu-toolchain/build-binutils-newlib/libiberty/libiberty.a macos
cp /scratch/carsteng/git/freedom-tools-tdl/obj/x86_64-apple-darwin/build/riscv-gnu-toolchain/build-binutils-newlib/intl/libintl.a macos
cp /scratch/carsteng/git/freedom-tools-tdl/obj/x86_64-apple-darwin/build/riscv-gnu-toolchain/build-binutils-newlib/zlib/libz.a macos
/Library/Developer/CommandLineTools/usr/bin/make -C Debug all
Building file: ../src/dqr.cpp
Invoking: GCC C++ Compiler
g++ -I"../include" -D OSX -std=c++11 -O0 -g3 -Wall -Wformat=0 -c -fmessage-length=0 -MMD -MP -MF"dqr.d" -MT"dqr.o" -o "dqr.o" "../src/dqr.cpp"
In file included from ../src/dqr.cpp:34:
../include/trace.hpp:303:1: warning: 'NexusMessageSync' defined as a struct here but previously declared as a class [-Wmismatched-tags]
struct NexusMessageSync {
^
../include/dqr.hpp:491:2: note: did you mean struct here?
        class NexusMessageSync *messageSync[DQR_MAXCORES];
        ^~~~~
        struct
1 warning generated.
Finished building: ../src/dqr.cpp
 
Building file: ../src/main.cpp
Invoking: GCC C++ Compiler
g++ -I"../include" -D OSX -std=c++11 -O0 -g3 -Wall -Wformat=0 -c -fmessage-length=0 -MMD -MP -MF"main.d" -MT"main.o" -o "main.o" "../src/main.cpp"
Finished building: ../src/main.cpp
 
Building file: ../src/trace.cpp
Invoking: GCC C++ Compiler
g++ -I"../include" -D OSX -std=c++11 -O0 -g3 -Wall -Wformat=0 -c -fmessage-length=0 -MMD -MP -MF"trace.d" -MT"trace.o" -o "trace.o" "../src/trace.cpp"
In file included from ../src/trace.cpp:35:
../include/trace.hpp:303:1: warning: 'NexusMessageSync' defined as a struct here but previously declared as a class [-Wmismatched-tags]
struct NexusMessageSync {
^
../include/dqr.hpp:491:2: note: did you mean struct here?
        class NexusMessageSync *messageSync[DQR_MAXCORES];
        ^~~~~
        struct
../src/trace.cpp:1340:42: warning: expression result unused [-Wunused-value]
                                state[currentCore = TRACE_STATE_ERROR];
                                ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
2 warnings generated.
Finished building: ../src/trace.cpp
 
Building target: dqr
Invoking: GCC C++ Linker
g++ -L../lib/macos  -o dqr ./dqr.o ./main.o ./trace.o  -lbfd -lopcodes -liberty -lz -lintl -liconv
Finished building target: dqr
 
Building file dqr_wrap.cpp
Invoking: SWIG Compiler
swig -package com.sifive.trace -outdir com/sifive/trace -java -c++ -o dqr_wrap.cpp -I../include ../include/dqr.i
javac com/sifive/trace/*.java
jar cf TraceDecoder.jar com/sifive/trace/*
Finished building: dqr_wrap.cpp
 
Building file dqr_wrap.o
Invoking: GCC C++ Compiler
g++ -D OSX -std=c++11 -O0 -g3 -Wall -Wformat=0 -D OSX -std=c++11 -O0 -g3 -Wall -Wformat=0 -c dqr_wrap.cpp -I"../include" -I"/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac" -I"/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac/darwin"
dqr_wrap.cpp:181:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^~~~~~~
1 error generated.
make[2]: *** [dqr_wrap.o] Error 1
make[1]: *** [Debug] Error 2

**Comment by cgsfv** [comment]
$ which java
/usr/bin/java

**Comment by bradseevers** [comment]
how about

which javac

Thanks,

-brad

**Comment by cgsfv** [comment]
$ which javac
/usr/bin/javac

**Comment by bradseevers** [comment]
Can you send me the trace-decoder make build log?

Thanks,

-brad

**Comment by cgsfv** [comment]
It was in the comment right before the which java comment :-)

**Comment by bradseevers** [comment]
Got it! Thanks!

**Comment by bradseevers** [comment]
Could you send me the makefile.init?  Not sure it is reflecting the latest
changes.

-brad

**Comment by bradseevers** [comment]
Never mind - think I found an issue.

**Comment by cgsfv** [comment]
It builds on my mac - great work!
Where is the trace-decoder swig library - I cannot find it in the tar.gz package built?

**Comment by bradseevers** [comment]
It should be in the trace-decoder/Debug lib. The windows version will be
dqr.dll. On Linux and mac will will be libdqr.so.

-brad

**Comment by cgsfv** [comment]
it's not in any of the bin/trace-decoder...tar.gz files
did you copy the new files into the install directory?

**Comment by bradseevers** [comment]
No, I don’t copy the darn executable or the far lis anywhere

**Comment by cgsfv** [comment]
If you take a look at the "$(OBJDIR)/%/build/trace-decoder/trace-decoder/stamp" target in the freedom-tools Makefile, I added the copying of the original artifacts.

It would be really nice if this part was added to a "make install" target in the trace-decoder makefile just like it is done for binutils, gdb, etc., as the trace-decoder should have the knowledge of what to copy.

**Comment by bradseevers** [comment]
I will take a look at it.

-brad

**Comment by bradseevers** [comment]
That should have been the dqr executable, not the darn executable! Can't
type today!

-brad

**Comment by bradseevers** [comment]
Carsten,

I will add an install target to the trace-decoder makefile if you update
the freedom-tools Makefile to use it!

-brad

**Comment by cgsfv** [comment]
Perfect - thanks.
Will it be like: make install INSTALLPATH=...

**Comment by bradseevers** [comment]
Yes, just like that!

-brad

**Comment by cgsfv** [comment]
Good - just let me know when you have update the freedom-tools branch to point to your updated trace-decoder, then I will try it out immediately.

**Comment by cgsfv** [comment]
Just updated the freedom-tools Makefile, in case you wanted to try it out.

**Comment by bradseevers** [comment]
You are ahead of me!  I will get to work on this in a few minutes. Thanks!!

-brad

**Comment by bradseevers** [comment]
Carsten,,

I have checked in changes to the trace-decoder makefile to support "make
install INSTALLPATH=..."  I have not yet updated the submodule reference -
I am checking freedom-tools out now, and it is SLOW. I will let you know
when I get that done.

Thanks,

-brad

**Comment by bradseevers** [comment]
Carsten,

Last evening I checked in updates to the trace encoder for install support,
but I have been unable to update the freedom-tools trace-encoder-libs
branch.

Something happened to my copy on my machine, and I have been unable to
successfully git it.

Could you do the update? I will continue to attemp to get everything off of
github, and if I am successful, I will let you know.

Thanks,

-brad

**Comment by cgsfv** [comment]
Sure - it's updated now.
I will try building again, and let you know how it goes.

**Comment by bradseevers** [comment]
Thanks Carsten!

-brad

**Comment by cgsfv** [comment]
With the CROSSPREFIX added to the make install, it builds on ubuntu as well for both linux and windows.
In the windows cross build, the bin and lib directories both also has empty linux directories next to the windows directories - it would be nice if it only had the windows directory.

**Comment by cgsfv** [comment]
Thinking about it, it would be nice if the macos, linux and windows directory levels were removed - making it easier to reference the items.

**Comment by cgsfv** [comment]
This is also how all the other packages are structured :-)

**Comment by bradseevers** [comment]
Okay - I will remove the extra level of directories.

-brad

**Comment by bradseevers** [comment]
Okay, changes are pushed to place stuff in bin and lib, and not in
bin/$(PLATFORM) and lib/$(PLATFORM).

You will need to update freedom-tool trace-decoder-libs branch to point to
latest, as I am still  having problems.

Thanks,

-brad

**Comment by cgsfv** [comment]
Great - I will update trace-decoder in freedom-tools.

One more request - I would like you to rename NEWLIBPATH to BINUTILSPATH, as that is what it really points to.

**Comment by bradseevers** [comment]
Okay - give me a few minutes and I will!

-brad

**Comment by bradseevers** [comment]
Message failed to send. I updated the trace-decoder makefiles for the
BINUTILSPATH. Can you update freedom-tools to point to it? And use the
BINUTILSPATH when building the trace decoder?

Thanks,

-brad

**Comment by cgsfv** [comment]
It builds fine on both ubuntu (incl. cross windows) and mac.
I add a binutils build step to the trace-decoder package build in freedom-tools, so that the trace-decoder can be built alone, simply by: make trace-decoder

**Comment by bradseevers** [comment]
Looks good Carsten!

Thanks,

-brad

**Comment by cgsfv** [comment]
And now it also builds on Centos6.

**Comment by bradseevers** [comment]
Thats great! Does that mean we are done and it can be merged into master?

-brad

**Comment by cgsfv** [comment]
Yes, I think we should merge it master.
But all the packages built needs to be tested on all the platforms before we can say we are done.

**Comment by bradseevers** [comment]
Sounds good Carsten!

**Pull request merged**
